type OwnershipTransferred @entity(immutable: true) {
  id: Bytes!
  previousOwner: Bytes! # address
  newOwner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type TokenCreated @entity(immutable: true) {
  id: Bytes!
  owner: Bytes! # address
  token: Bytes! # address
  name: String! # string
  ticker: String! # string
  initialAmount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type VestingScheduleCreated @entity(immutable: true) {
  id: Bytes!
  vestingContract: Bytes! # address
  beneficiary: Bytes! # address
  totalAmount: BigInt! # uint256
  start: BigInt! # uint256
  periodDuration: BigInt! # uint256
  totalPeriods: BigInt! # uint256
  tokenName: String! # string
  tokenSymbol: String! # string
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  token: Bytes! # address
}
